permalink: pretty
theme: jekyll_patternbot

patternbot:
  title: "Let's Get Lit"
  layouts:
    default: |
      The default layout should be used for almost every page, it includes the website's primary header and footer.
  description: |
    A website selling home-made candles as well as accessories for candles.
  font_url: "https://fonts.googleapis.com/css?family=Raleway:400,500,700&display=swap"
  colors:
    background: "--color-neutral"
    accent: "--color-secondary"
    patterns:
      brand.logos: "--color-primary"
  rationales:
    typefaces.primary:  |
      Raleway was selected because of its open and feminine appearance and for its tall x-height. Raleway is to be used for all the website's type.
    colors.primary: |
      The primary colour is black. It was chosen for its modern yet classy look with the contrast against the white and pale shades of pink and purple. It's used throughout the website, in the type in all body-copy as well as all headings. The colour is also used in the background of the header and footer.
    colors.secondary: |
      The secondary colour is a shade of lavender which is a popular scent for candles and is also very feminine which is keeping with the target audience. This colour is used in all the buttons except for the navigation.
    colors.accent: |
      The accent colour is a light shade of pink. It is used in the background for headers and text areas of cards. It is not used in the background for the text on the product page.
    colors.neutral: |
      The neutral colour is white. It is used as the background of the website and in the type in the buttons, footer, and header.
collections:
  products:
    output: true
