permalink: pretty
theme: jekyll_patternbot

patternbot:
  font_url: "https://fonts.googleapis.com/css?family=Raleway:400,500,700&display=swap"
  colors:
    patterns:
      brand.logos: "--color-primary"
