title: "Cards"
description: |
  The candle cards and product cards should be used on the home page and the products page to entice a viewer to click and learn more about the product. The banners are to only be used on the home page.

patterns:
  candle:
    title: "Candle"
    description: |
      To be used on the home and products page.
    width: "20em"
    background: "#fff"
  spring-banner:
    fields:
      - name: heading
        type: string
        example: "Looking forward to spring? So are we!"
      - name: text
        type: string
        example: "Shop our collection today to find what's right for you in time for the new season!"
    title: "Spring Banner"
    description: |
      To be used at the top of the home page as the first banner.
    background: "color-primary"
  team-banner:
    title: "Team Banner"
    description: |
      To be used at the bottom of the home page as the last banner.
    background: "color-primary"
  product-card:
    title: "Product Card"
    description: |
      To be used on the home and products list page when using a card for a candle. There's a placeholder for an image above the pink area.
    width: "20em"
    background: "#fff"
